version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify your Python version
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt pylint
  pre_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py
      - pylint $CODEBUILD_SRC_DIR/food_ordering_proj/*.py
artifacts:
  files:
    - '**/*'
