# Generated by Django 3.2.22 on 2023-10-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
